apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  # IRSA를 사용하는 경우 여기에 annotation을 추가합니다:
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/YOUR_LBC_IAM_ROLE