name: Terraform Deploy (Exclude IAM)

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-northeast-2
  CLUSTER_NAME: daenamu-test

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.1

      - name: Download previous tfstate (if exists)
        uses: actions/download-artifact@v4.3.0
        with:
          name: terraform-state
        continue-on-error: true

      - name: Restore tfstate if available
        run: |
          if [ -d terraform-state ]; then
            mv terraform-state/terraform.tfstate .
            echo "Previous state restored"
          else
            echo "No previous state found"
          fi

      # ✅ IAM 관련 .tf 파일 제외
      - name: Temporarily disable IAM-related files
        run: |
          mkdir skipped || true
          mv iam.tf skipped/ || true
          mv sa.tf skipped/ || true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # (선택) .tf 파일 복원
      - name: Restore IAM files (optional)
        run: |
          mv skipped/iam.tf . || true
          mv skipped/sa.tf . || true

      - name: Generate kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ env.CLUSTER_NAME }} \
            --region ${{ env.AWS_REGION }}

      - name: Wait for nodes to be ready
        run: |
          for i in {1..10}; do
            echo "Checking nodes (attempt $i)..."
            if kubectl get nodes; then
              echo "Nodes are ready."
              break
            fi
            sleep 15
          done

      - name: Upload updated tfstate
        uses: actions/upload-artifact@v4.6.2
        with:
          name: terraform-state
          path: terraform.tfstate
